### PR TITLE
Use the new GlobalAlloc trait

### PR DESCRIPTION
**Pull request by SimonSapin**
This is part of https://github.com/rust-lang/rust/pull/49669.

### CODE REVIEW

**Comment by SimonSapin** [comment]
For now, please copy this branch into this repo so that the rust-lang/rust submodule can fetch it: 

```
git fetch https://github.com/SimonSapin/nomicon global-alloc
git push https://github.com/rust-lang-nursery/nomicon FETCH_HEAD:global-alloc
```

**Comment by Gankro** [comment]
Wondering if it would be better to use `*mut _` casts to avoid ever importing Opaque?

**Comment by Gankro** [comment]
UHHH I don't think we were supposed to do that??

**Comment by alexcrichton** [comment]
Sorry this merged in rust-lang/rust and the submodul wasn't updating so this needed to be merged in somehow.

@Gankro are you referring to this PR or the content of the rust-lang/rust PR?

**Comment by Gankro** [comment]
I thought the branch dance had to be done to even land anything..?

**Comment by alexcrichton** [comment]
I thought so too!

**Comment by SimonSapin** [comment]
Wait, so https://github.com/rust-lang/rust/pull/49669 passed Travis without this branch being in this repo at all?

**Comment by alexcrichton** [comment]
Apparently!

**Pull request merged**
