### PR TITLE
Fixed  of compilation on latest nightly locally, but still issue on playg…

### PR DESCRIPTION
**Pull request by izderadicka**
Fixing #70, works fine with local nightly, but but looks like very latest nightly has changed again.

### CODE REVIEW

**Comment by izderadicka** [comment]
Ok with latest update of nightly got same issue.

**Comment by RalfJung** [comment]
Seems like https://github.com/rust-lang-nursery/nomicon/pull/73 did the same thing and hence broke this PR?

**Comment by izderadicka** [comment]
@RalfJung  yes I think it's  almost the same except two things:
1. I think there is logical error in Drain as both Iterator and DoubleEndedIterator impl are using next_back from underlying iterator- so both going in same direction - backwards. 
2. I added some tests to vec-final.

Remainig diffs are just formating ( and I used System instead of Global but Global seems to be right name now).
If you're interested in two changes mentioned above let me know I'll  pull latest version and leave just these two.

**Comment by RalfJung** [comment]
> I think there is logical error in Drain as both Iterator and DoubleEndedIterator impl are using next_back from underlying iterator- so both going in same direction - backwards.

That looks like a typo indeed but it was not introduced by #73. I'd prefer if @Gankro would take a look.^^

> I added some tests to vec-final.

I'm always in favor of tests. :D Do you know if `mdbook test` will run these tests?

**Comment by Gankro** [comment]
CC @steveklabnik on mdbook

**Comment by steveklabnik** [comment]
`mdbook test` runs `rustdoc --test` on each of your files, so it should.

**Comment by RalfJung** [comment]
So @izderadicka would you like to make a new PR with your tests, and with the fix to `next_back` (that is likely needed to make the tests pass)?

**Comment by izderadicka** [comment]
@RalfJung will look at it next week as I'm off this week. Closing this one.

**Pull request closed without merging**
