### PR TITLE
further clarify C11 and C/C++11 terminology

### PR DESCRIPTION
**Pull request by RalfJung**
Thanks @petrochenkov for confirming that C++ is the origin of this model.

### CODE REVIEW

**Comment by RalfJung** [comment]
> Question: does the reference say anything that needs to be updated as well?

I haven't read most of it, so no idea.^^

`rg C11` gives no results.

**Comment by Centril** [comment]
> `rg C11` gives no results.

Neither does "Concurrency", "Atomic", ... :)

**Comment by Centril** [comment]
The book doesn't seem to mention this at all so we're good there.

**Pull request merged**
