### PR TITLE
Update for https://github.com/rust-lang/rust/pull/42959

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by Gankro** [comment]
ping me when this is ready to land

**Comment by SimonSapin** [comment]
I suppose we still have to figure out which parts of #42959 are desired. In the meantime, could you push this to a branch of this repo so that https://travis-ci.org/rust-lang/rust/jobs/253789889 doesn’t fail to update the submodule?

**Comment by Gankro** [comment]
uhh is it possible for you to submit the PR to a branch?

**Comment by SimonSapin** [comment]
Yes, but a branch other than master needs to exist first.

Or you can do something like `git fetch origin pull/32/head && git push origin FETCH_HEAD:nonzero-checked`

**Comment by Gankro** [comment]
if only there were SOME WAY to not have to deal with circular dependencies..........................

**Comment by Gankro** [comment]
Added branch https://github.com/rust-lang-nursery/nomicon/tree/42959

**Comment by Gankro** [comment]
#33 is the replacement for this

**Comment by Gankro** [comment]
something something need to merge this to master properly

**Pull request merged**
