### PR TITLE
Update for field reordering

### PR DESCRIPTION
**Pull request by bennyyip**
https://github.com/rust-lang/rust/blob/master/RELEASES.md
https://github.com/rust-lang/rust/pull/40377

### CODE REVIEW

**Comment by Gankro** [comment]
Hey sorry for the delay! I think it would be better to just remove the note altogether? I think I just added this to avoid getting complaints about "why doesn't the compiler do this the book said so!"

what do you think?

**Comment by bennyyip** [comment]
Great idea! Moreover, maybe we should replace it with something like: "Rust compiler does field reordering when not using repr(c)", make it more clear to the reader.

**Comment by Gankro** [comment]
I think that's the whole point of this section, (and the one on repr(C)), so I don't think that will be necessary.

**Comment by bennyyip** [comment]
Ok, I removed the notes.

**Pull request merged**
