### PR TITLE
Don’t recommend empty enums for opaque types

### LINKED ISSUE #29: FFI section suggests dangerous practice of using empty opaque type
The FFI section of the Nomicon currently suggests to use an empty type for "opaque pointer types". That seems pretty dangerous. This came up in the discussion at <https://github.com/rust-lang/rfcs/pull/1861>, and also in <https://internals.rust-lang.org/t/recent-change-to-make-exhaustiveness-and-uninhabited-types-play-nicer-together/4602> many were not happy with using the empty type here.

Until we have proper opaque types, the safer suggestion seems to be do use a ZST with a private field, rather than an empty type. Then at least the type is not actively lying.

### PR DESCRIPTION
**Pull request by RalfJung**
Supersedes https://github.com/rust-lang-nursery/nomicon/pull/44 (which seems to have gone stale).

Fixes #29.

### CODE REVIEW

**Comment by gnzlbg** [comment]
LGTM. 

cc @ubsan @eddyb @steveklabnik

**Comment by ubsan** [comment]
I'd rather have an explicit `opaque` type in the language, but in lieu of that, this is better than before.

**Comment by gnzlbg** [comment]
@ubsan there is an already merged RFC for that (https://github.com/rust-lang/rust/issues/43467). This PR only updates the nomicon with better practices for the features that the language currently has. Once extern types are finished, this will need updating again.

**Comment by ubsan** [comment]
@gnzlbg ooh! cool! I've never seen that! :D

**Pull request merged**
